#!/usr/bin/env python3
import sys

from Modules.commands import (
    leaf_branch,
    leaf_checkout,
    leaf_diff,
    leaf_help,
    leaf_ignore,
    leaf_init,
    leaf_log,
    leaf_merge,
    leaf_restore,
    leaf_save,
    leaf_status,
    leaf_version,
)


def main():
    if len(sys.argv) < 2:
        return

    cmd = sys.argv[1]
    if cmd == "init":
        leaf_init()
    elif cmd == "save":
        leaf_save(" ".join(sys.argv[2:]))
    elif cmd == "log":
        leaf_log()
    elif cmd == "restore":
        if len(sys.argv) < 3:
            print("🍂 Missing commit id")
            return
        leaf_restore(sys.argv[2])
    elif cmd == "status":
        leaf_status()
    elif cmd == "diff":
        leaf_diff(sys.argv[2] if len(sys.argv) == 3 else None)
    elif cmd == "ignore":
        if len(sys.argv) < 3:
            print("🍂 Missing file/folder name")
            return
        leaf_ignore(" ".join(sys.argv[2:]))
    elif cmd == "branch":
        leaf_branch(sys.argv[2] if len(sys.argv) > 2 else None)
    elif cmd == "checkout":
        if len(sys.argv) < 3:
            print("🍂 Missing branch name")
            return
        leaf_checkout(sys.argv[2])
    elif cmd == "merge":
        if len(sys.argv) < 3:
            print("🍂 Missing branch name to merge")
            return
        leaf_merge(sys.argv[2])
    elif cmd in {"help", "-h", "--help"}:
        leaf_help()
    elif cmd in {"version", "v", "-v"}:
        leaf_version()


if __name__ == "__main__":
    main()
