#!/usr/bin/env python3
import sys

from Modules.commands import (
    leaf_branch,
    leaf_checkout,
    leaf_clone,
    leaf_diff,
    leaf_fsck,
    leaf_export_git,
    leaf_ignore,
    leaf_import_git,
    leaf_init,
    leaf_log,
    leaf_merge,
    leaf_reset,
    leaf_restore,
    leaf_revert,
    leaf_save,
    leaf_status,
    leaf_tag,
    leaf_version,
)
from Modules.staging import leaf_add
from Modules.help import leaf_help


def main():
    if len(sys.argv) < 2:
        from GUI.main import run
        raise SystemExit(run())

    cmd = sys.argv[1]
    if cmd == "init":
        leaf_init()
    elif cmd == "save":
        leaf_save(" ".join(sys.argv[2:]))
    elif cmd == "add":
        leaf_add(" ".join(sys.argv[2:]) or ".")
    elif cmd == "reset":
        if len(sys.argv) > 2 and sys.argv[2] in {"--hard", "--soft"}:
            leaf_reset(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
        else:
            leaf_reset(sys.argv[2] if len(sys.argv) > 2 else None)
    elif cmd == "revert":
        if len(sys.argv) < 3:
            print("🍂 Missing commit id")
            return
        leaf_revert(sys.argv[2])
    elif cmd == "log":
        leaf_log()
    elif cmd == "restore":
        if len(sys.argv) < 3:
            print("🍂 Missing commit id")
            return
        leaf_restore(sys.argv[2])
    elif cmd == "status":
        leaf_status()
    elif cmd == "diff":
        leaf_diff(sys.argv[2] if len(sys.argv) == 3 else None)
    elif cmd == "ignore":
        if len(sys.argv) < 3:
            print("🍂 Missing file/folder name")
            return
        leaf_ignore(" ".join(sys.argv[2:]))
    elif cmd == "branch":
        leaf_branch(sys.argv[2] if len(sys.argv) > 2 else None, sys.argv[3] if len(sys.argv) > 3 else None)
    elif cmd == "checkout":
        if len(sys.argv) < 3:
            print("🍂 Missing branch name")
            return
        leaf_checkout(sys.argv[2])
    elif cmd == "merge":
        if len(sys.argv) < 3:
            print("🍂 Missing branch name to merge")
            return
        leaf_merge(sys.argv[2])
    elif cmd == "tag":
        leaf_tag(sys.argv[2] if len(sys.argv) > 2 else None, sys.argv[3] if len(sys.argv) > 3 else None)
    elif cmd in {"remote", "fetch", "pull", "push"}:
        print("🍂 Remote repository commands are currently disabled")
    elif cmd == "clone":
        if len(sys.argv) < 3:
            print("🍂 Missing source path")
            return
        leaf_clone(sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
    elif cmd == "import-git":
        leaf_import_git()
    elif cmd == "export-git":
        leaf_export_git()
    elif cmd == "fsck":
        leaf_fsck()
    elif cmd in {"help", "-h", "--help"}:
        leaf_help()
    elif cmd in {"version", "v", "-v"}:
        leaf_version()


if __name__ == "__main__":
    main()
