from leaf_test_utils import main_wrapper


def run(ctx):
    ctx.repo.mkdir()
    ctx.command(["leaf", "init"])
    ctx.write("story.txt", "base\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "base"])
    base = ctx.commit_ids()[-1]
    ctx.write("story.txt", "base\nfeature draft\n")
    ctx.command(["leaf", "branch", "feature"])
    ctx.command(["leaf", "branch", "feature"], contains="Branch already exists")
    ctx.command(["leaf", "branch", "bad", "not-a-commit"], contains="Invalid commit id")
    ctx.command(["leaf", "checkout", "missing"], contains="Unknown branch")
    branch_list = ctx.command(["leaf", "branch"])
    ctx.check("* main" in branch_list.stdout and "  feature" in branch_list.stdout, "Branch list marks current branch and shows feature")
    ctx.command(["leaf", "checkout", "feature"], contains="feature")
    ctx.command(["leaf", "merge", "feature"], contains="Already on feature")
    ctx.assert_file("story.txt", "base\n")
    ctx.command(["leaf", "checkout", "main"], contains="main")
    ctx.assert_file("story.txt", "base\nfeature draft\n")
    ctx.command(["leaf", "reset", "--hard", base])
    ctx.assert_file("story.txt", "base\n")
    ctx.command(["leaf", "checkout", "feature"], contains="feature")
    ctx.write("story.txt", "base\nfeature draft\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "feature commit"])
    feature_tip = ctx.commit_ids()[-1]
    ctx.command(["leaf", "checkout", "main"], contains="main")
    ctx.assert_file("story.txt", "base\n")
    ctx.write("main.txt", "main only\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "main commit"])
    ctx.command(["leaf", "merge", "missing"], contains="Unknown branch")
    ctx.command(["leaf", "merge", "feature"])
    ctx.assert_file("story.txt", "base\nfeature draft\n")
    ctx.assert_file("main.txt", "main only\n")
    branches = ctx.load_json(".leaf/branches.json")
    ctx.check(branches["feature"] == feature_tip and branches["main"] != base, "Branch pointers updated")

    ctx.command(["leaf", "branch", "conflict-a"])
    ctx.command(["leaf", "branch", "conflict-b"])
    ctx.command(["leaf", "checkout", "conflict-a"])
    ctx.write("staged-block.txt", "blocked\n")
    ctx.command(["leaf", "add", "."], contains="Staged")
    ctx.command(["leaf", "merge", "conflict-b"], contains="Commit or reset staged changes before merging")
    ctx.command(["leaf", "reset"], contains="Cleared staging area")
    ctx.write("conflict.txt", "A\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "conflict a"])
    ctx.command(["leaf", "checkout", "conflict-b"])
    ctx.write("conflict.txt", "B\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "conflict b"])
    ctx.command(["leaf", "checkout", "conflict-a"])
    conflict = ctx.command(["leaf", "merge", "conflict-b"])
    ctx.check("conflicts" in conflict.stdout.lower(), "Merge reported conflict")
    ctx.check("<<<<<<<" in ctx.read("conflict.txt"), "Conflict markers written")
    ctx.write("conflict.txt", "resolved\n")
    ctx.command(["leaf", "merge", "--continue"])
    ctx.assert_file("conflict.txt", "resolved\n")
    ctx.command(["leaf", "checkout", "conflict-b"])
    ctx.command(["leaf", "branch", "abort-a"])
    ctx.command(["leaf", "branch", "abort-b"])
    ctx.command(["leaf", "checkout", "abort-a"])
    ctx.write("abort.txt", "left\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "abort left"])
    before_abort = ctx.read("abort.txt")
    ctx.command(["leaf", "checkout", "abort-b"])
    ctx.write("abort.txt", "right\n")
    ctx.command(["leaf", "add", "."])
    ctx.command(["leaf", "save", "abort right"])
    ctx.command(["leaf", "checkout", "abort-a"])
    ctx.command(["leaf", "merge", "abort-b"])
    ctx.command(["leaf", "merge", "--abort"])
    ctx.assert_file("abort.txt", before_abort)
    ctx.command(["leaf", "fsck"], contains="OK")


if __name__ == "__main__":
    main_wrapper(__file__, run)
